# Generated by Django 5.1.7 on 2025-06-05 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("tipo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_entrada", models.IntegerField()),
                ("data_entrada", models.DateField()),
                ("documento_referencia", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LocalEstocagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("endereco", models.TextField()),
                ("capacidade_maxima", models.IntegerField(blank=True, null=True)),
                ("temperatura_controlada", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_lote", models.CharField(max_length=100)),
                ("data_validade", models.DateField()),
                ("quantidade", models.IntegerField()),
                ("origem", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("codigo_barras", models.CharField(max_length=100)),
                ("fabricante", models.CharField(max_length=100)),
                ("temperatura_armazenamento", models.CharField(max_length=50)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Saida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_saida", models.IntegerField()),
                ("motivo", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                ("data_saida", models.DateField()),
            ],
        ),
    ]
