# Generated by Django 5.1.7 on 2025-06-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estoque", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="usuarios.usuario"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="armazenado_em",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="estoque.localestocagem"
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="estoque.lote"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="estoque.categoria"
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="estoque.produto"
            ),
        ),
        migrations.AddField(
            model_name="saida",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="estoque.lote"
            ),
        ),
        migrations.AddField(
            model_name="saida",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="usuarios.usuario"
            ),
        ),
    ]
