# Generated by Django 5.1.7 on 2025-06-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("data_requisicao", models.DateField()),
                ("observacao", models.TextField(blank=True)),
                (
                    "local_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisicoes_destino",
                        to="estoque.localestocagem",
                    ),
                ),
                (
                    "local_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisicoes_origem",
                        to="estoque.localestocagem",
                    ),
                ),
            ],
        ),
    ]
